---
revision:
  default: testing
  production: testing
migrate:
  default: false
  _default: true
migration_command:
  default: ls /tmp
after_checkout:
  execute_touch:
    command: 'touch /tmp/something'
